version: '3'

services:
  change3d-api:
    build:
      context: ..
      dockerfile: ./change3d_api_docker/Dockerfile
    image: change3d-api-built:latest
    container_name: change3d-api
    ports:
      - "8000:8000"
    volumes:
      # 修改挂载配置，使用完整路径
      - ./:/app/change3d_api_docker
      - ../change3d_docker:/app/change3d_docker
      # 共享数据目录 - 确保写权限
      - ./t1:/app/change3d_api_docker/t1:rw
      - ./t2:/app/change3d_api_docker/t2:rw
      - ./output:/app/change3d_api_docker/output:rw
      # 检查点目录
      - ../change3d_docker/checkpoint:/app/change3d_docker/checkpoint:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
      - KMP_DUPLICATE_LIB_OK=TRUE
      # 添加文件权限环境变量
      - UMASK=0000
      # 添加调试环境变量
      - DEBUG=1
      - LOG_LEVEL=DEBUG
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#"上传-处理-下载"